[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.115.6",
    "pandas==2.2.3",
    "playwright==1.49.0",
    "uvicorn==0.32.1",
]
